'use strict';

/**
 * generate-tests.js
 *
 * Takes a DiffContext from analyze-diff.js, builds targeted prompts,
 * calls the AI API, and writes Cypress test files to the output directory.
 *
 * Usage (standalone):
 *   node scripts/generate-tests.js --diff-file diff-context.json
 *   node scripts/generate-tests.js --repo server --range HEAD~1
 */

const OpenAI = require('openai');
const fs = require('fs-extra');
const path = require('path');
const chalk = require('chalk');
const ora = require('ora');
const { config, validate } = require('./config');
const { analyzeDiff } = require('./analyze-diff');

// ─── AI Client Factory ────────────────────────────────────────────────────────

function createAIClient() {
  if (config.ai.provider === 'azure') {
    return new OpenAI.AzureOpenAI({
      apiKey: config.ai.azure.apiKey,
      endpoint: config.ai.azure.endpoint,
      apiVersion: config.ai.azure.apiVersion,
      deployment: config.ai.azure.deployment,
    });
  }
  return new OpenAI.OpenAI({ apiKey: config.ai.openai.apiKey });
}

function getModel() {
  return config.ai.provider === 'azure'
    ? config.ai.azure.deployment
    : config.ai.openai.model;
}

// ─── Prompt Building ──────────────────────────────────────────────────────────

function loadPrompt(filename) {
  const promptPath = path.join(config.generation.promptsDir, filename);
  if (!fs.existsSync(promptPath)) {
    throw new Error(`Prompt file not found: ${promptPath}`);
  }
  return fs.readFileSync(promptPath, 'utf8');
}

/**
 * Builds the diff summary section of the prompt.
 * Lists changed files with their categories.
 */
function buildDiffSummary(files) {
  return files
    .map(f => `  [${f.changeType.toUpperCase()}] (${f.category}) ${f.filePath}`)
    .join('\n');
}

/**
 * Builds the detailed diff+content section of the prompt.
 * Includes the diff AND current file content for context.
 */
function buildDiffDetails(files) {
  return files.map(f => {
    const sections = [];
    sections.push(`### File: ${f.filePath} [${f.changeType}] [${f.category}]`);

    if (f.content) {
      sections.push(`**Current Content:**\n\`\`\`\n${f.content}\n\`\`\``);
    }

    if (f.diff && f.diff !== '[diff unavailable]') {
      sections.push(`**Diff:**\n\`\`\`diff\n${f.diff}\n\`\`\``);
    }

    return sections.join('\n\n');
  }).join('\n\n---\n\n');
}

/**
 * Builds the full AI prompt for a given repo diff.
 */
function buildPrompt(repoDiff) {
  const promptFile = repoDiff.repoType === 'backend'
    ? 'api-test-prompt.md'
    : 'e2e-test-prompt.md';

  const template = loadPrompt(promptFile);
  const diffSummary = buildDiffSummary(repoDiff.files);
  const diffDetails = buildDiffDetails(repoDiff.files);

  return template
    .replace('{diff_summary}', diffSummary)
    .replace('{diff_details}', diffDetails);
}

// ─── AI Call ─────────────────────────────────────────────────────────────────

/**
 * Calls the AI API with the given prompt and returns the raw response text.
 */
async function callAI(client, prompt) {
  const model = getModel();

  const response = await client.chat.completions.create({
    model,
    temperature: config.generation.temperature,
    messages: [
      {
        role: 'system',
        content: 'You are an expert QA engineer. Always respond with valid JSON only, no extra text.',
      },
      {
        role: 'user',
        content: prompt,
      },
    ],
  });

  return response.choices[0]?.message?.content || '{}';
}

/**
 * Extracts JSON from AI response (handles markdown code blocks).
 */
function extractJSON(rawResponse) {
  let text = rawResponse.trim();
  if (text.startsWith('```json')) text = text.slice(7);
  else if (text.startsWith('```')) text = text.slice(3);
  if (text.endsWith('```')) text = text.slice(0, -3);
  return text.trim();
}

// ─── File Writing ─────────────────────────────────────────────────────────────

/**
 * Returns a safe subdirectory name for a repo (e.g., 'platform-server' → 'server').
 */
function repoSubDir(repoName) {
  return repoName.replace('platform-', '');
}

/**
 * Writes a single generated test file to disk.
 * Adds a header comment indicating it was auto-generated.
 */
function writeTestFile(repoName, testFile, diffRange) {
  const subDir = repoSubDir(repoName);
  const outputDir = path.join(config.generation.outputDir, subDir);
  fs.ensureDirSync(outputDir);

  const header = [
    '/**',
    ` * AUTO-GENERATED by platform-test-automation`,
    ` * Repo: ${repoName}`,
    ` * Diff range: ${diffRange}`,
    ` * Generated: ${new Date().toISOString()}`,
    ` * Description: ${testFile.description || ''}`,
    ' *',
    ' * ⚠️  This file is auto-generated. Manual edits may be overwritten.',
    ' *    Move tests to cypress/e2e/baseline/ if you want to preserve them.',
    ' */',
    '',
  ].join('\n');

  const fullContent = header + (testFile.content || '');
  const outputPath = path.join(outputDir, testFile.fileName);

  fs.writeFileSync(outputPath, fullContent, 'utf8');
  return outputPath;
}

// ─── Core: generate tests for one repo ───────────────────────────────────────

/**
 * Generates Cypress tests for a single RepoDiff.
 * Returns an array of { filePath, testCount } for reporting.
 */
async function generateForRepo(client, repoDiff) {
  const { repoName, repoType, files, diffRange } = repoDiff;

  if (files.length === 0) {
    console.log(chalk.yellow(`  ⚠ No relevant changes in ${repoName}, skipping.`));
    return [];
  }

  console.log(chalk.blue(`\n🤖 Generating tests for ${repoName} (${files.length} changed files)...`));

  // Group files by meaningful test boundary (avoid one giant prompt)
  // Strategy: batch into groups of up to 5 files, one AI call per group
  const batchSize = 5;
  const batches = [];
  for (let i = 0; i < files.length; i += batchSize) {
    batches.push(files.slice(i, i + batchSize));
  }

  const results = [];

  for (let batchIdx = 0; batchIdx < batches.length; batchIdx++) {
    const batch = batches[batchIdx];
    const batchLabel = `Batch ${batchIdx + 1}/${batches.length}`;

    const spinner = ora(`  ${batchLabel} — calling AI (${repoType} tests)...`).start();

    try {
      // Build a RepoDiff with only this batch's files
      const batchRepoDiff = { ...repoDiff, files: batch };
      const prompt = buildPrompt(batchRepoDiff);

      const rawResponse = await callAI(client, prompt);
      const jsonStr = extractJSON(rawResponse);
      const parsed = JSON.parse(jsonStr);

      spinner.succeed(`  ${batchLabel} — AI response received`);

      const testFiles = parsed.testFiles || [];
      const summary = parsed.summary || {};

      if (testFiles.length === 0) {
        console.log(chalk.yellow(`    ⚠ No test files generated for this batch.`));
        continue;
      }

      for (const testFile of testFiles) {
        if (!testFile.fileName || !testFile.content) {
          console.log(chalk.yellow(`    ⚠ Skipping incomplete test file entry.`));
          continue;
        }

        const writtenPath = writeTestFile(repoName, testFile, diffRange);
        const relPath = path.relative(path.resolve(__dirname, '..'), writtenPath);

        console.log(chalk.green(`    ✅ Written: ${relPath}`));
        if (testFile.coveredEndpoints) {
          console.log(chalk.gray(`       Endpoints: ${testFile.coveredEndpoints.join(', ')}`));
        }
        if (testFile.coveredScenarios) {
          console.log(chalk.gray(`       Scenarios: ${testFile.coveredScenarios.join(', ')}`));
        }

        results.push({
          filePath: writtenPath,
          fileName: testFile.fileName,
          description: testFile.description,
          testCount: summary.totalTestCases || 0,
        });
      }

    } catch (err) {
      spinner.fail(`  ${batchLabel} — generation failed: ${err.message}`);
      if (config.verbose) console.error(err);
    }
  }

  return results;
}

// ─── Public API ───────────────────────────────────────────────────────────────

/**
 * Main entry point: takes a DiffContext and generates all Cypress tests.
 *
 * @param {import('./analyze-diff').DiffContext} diffContext
 * @returns {Promise<{ generated: Array, totalFiles: number }>}
 */
async function generateTests(diffContext) {
  validate(); // Throws if AI config is missing

  const client = createAIClient();
  const allGenerated = [];

  for (const repoDiff of diffContext.repos) {
    const results = await generateForRepo(client, repoDiff);
    allGenerated.push(...results);
  }

  console.log(chalk.bold.green(`\n✨ Test generation complete: ${allGenerated.length} file(s) written`));
  return { generated: allGenerated, totalFiles: allGenerated.length };
}

module.exports = { generateTests };

// ─── CLI ──────────────────────────────────────────────────────────────────────
if (require.main === module) {
  const { Command } = require('commander');
  const program = new Command();

  program
    .name('generate-tests')
    .description('Generate Cypress tests from git diff using AI')
    .option('--diff-file <path>', 'Path to a DiffContext JSON file from analyze-diff.js')
    .option('--repo <name>', 'Repo to analyze on the fly: server | web | all', 'all')
    .option('--range <range>', 'Git diff range (used if --diff-file not provided)', config.diff.defaultRange)
    .parse(process.argv);

  const opts = program.opts();

  async function run() {
    let diffContext;

    if (opts.diffFile) {
      console.log(chalk.blue(`📄 Loading diff context from ${opts.diffFile}`));
      diffContext = fs.readJsonSync(opts.diffFile);
    } else {
      diffContext = await analyzeDiff({ repo: opts.repo, range: opts.range });
    }

    await generateTests(diffContext);
  }

  run().catch(err => {
    console.error(chalk.red('\n❌ Error:'), err.message);
    process.exit(1);
  });
}
